name: CI for lkpatcher and liblk

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git
          python -m pip install --upgrade pip
          pip install --upgrade git+https://github.com/R0rt1z2/liblk
          pip install --upgrade git+https://github.com/R0rt1z2/lkpatcher

      - name: Create output directory
        run: mkdir -p output

      - name: Run LK Patcher
        run: |
          echo "import sys
from liblk.LkImage import LkImage
from lkpatcher.patcher import LkPatcher

def main():
    lk_image = LkImage(sys.argv[1])
    partitions = lk_image.get_partition_list()
    print('Partitions:', partitions)
    patcher = LkPatcher(image=sys.argv[1], patches='patches.json')
    patched_image = patcher.patch(output='output/lk-patched.bin')
    print('Patched image saved as', patched_image)

if __name__ == '__main__':
    main()" > process_image.py
          python process_image.py lk.bin
